/**
 * Guía de uso de ESTA app para el asistente: "¿cómo escaneo una boleta?", "¿dónde agrego mi
 * tarjeta?", "¿se puede dividir una cuenta?". Los nombres de botones y pantallas son los
 * reales del código; si cambian en la app, hay que actualizarlos aquí.
 */
import type { KnowledgeEntry } from './knowledge'

export const APP_KNOWLEDGE: KnowledgeEntry[] = [
  /* ───────────── Registrar movimientos ───────────── */
  {
    id: 'registrar-gasto',
    kind: 'app',
    triggers: [
      'registrar un gasto',
      'registro un gasto',
      'anotar un gasto',
      'anoto un gasto',
      'agregar un gasto',
      'nuevo gasto',
      'ingresar un gasto',
      'boton del medio',
    ],
    title: 'Registrar un gasto',
    answer:
      'Toca el botón **+** del centro de la barra de abajo (o **Gasto** en el Inicio), escribe el monto y elige la categoría y con qué pagaste. La app **aprende tus lugares**: la próxima vez te sugiere la categoría, la cuenta y el monto de siempre.',
    steps: [
      'Toca el botón **+** de abajo o **Gasto** en el Inicio.',
      'Escribe el monto y, si quieres, **¿Dónde?** (ej: Líder, Uber).',
      'Elige la **Categoría** y en **Pagaste con** la cuenta o tarjeta.',
      'Toca **Guardar gasto**.',
    ],
    action: { label: 'Registrar gasto', kind: 'sheet', sheet: { kind: 'tx', type: 'expense' } },
    related: ['¿Cómo escaneo una boleta?', '¿Cómo anoto rápido escribiendo?', '¿Cómo anoto una compra en cuotas?'],
  },
  {
    id: 'registrar-ingreso',
    kind: 'app',
    triggers: [
      'registrar un ingreso',
      'registro un ingreso',
      'anotar un ingreso',
      'anoto un ingreso',
      'agregar un ingreso',
      'nuevo ingreso',
      'anotar mi sueldo',
      'anoto mi sueldo',
    ],
    title: 'Registrar un ingreso',
    answer:
      'Toca **Ingreso** en el Inicio, o el botón **+** y cambia arriba a **Ingreso**. Escribe el monto, de dónde viene y en qué cuenta entró la plata.',
    steps: [
      'Toca **Ingreso** en el Inicio (o **+** y elige **Ingreso**).',
      'Escribe el monto y **¿De dónde viene?** (ej: sueldo, cliente, venta).',
      'Elige la **Categoría** y en **Entra a** la cuenta donde llegó.',
      'Toca **Guardar ingreso**.',
    ],
    action: { label: 'Registrar ingreso', kind: 'sheet', sheet: { kind: 'tx', type: 'income' } },
    related: ['¿Cómo transfiero entre mis cuentas?', '¿Cómo creo una categoría?'],
  },
  {
    id: 'transferir-entre-cuentas',
    kind: 'app',
    triggers: [
      'transferir entre cuentas',
      'transferir entre mis cuentas',
      'transfiero entre mis cuentas',
      'pasar plata de una cuenta a otra',
      'mover plata entre cuentas',
      'registrar una transferencia',
      'saque plata del cajero',
      'sacar plata del cajero',
    ],
    title: 'Transferir entre tus cuentas',
    answer:
      'Usa **Transferir** cuando mueves plata entre tus propias cuentas, por ejemplo al sacar del cajero (de tu cuenta a **Efectivo**). **No cuenta como gasto ni como ingreso**: solo cambia los saldos.',
    steps: [
      'Toca **Transferir** en el Inicio o en **Más → Cuentas**.',
      'Escribe el monto.',
      'En **Desde** elige la cuenta de donde sale y en **Hacia** la cuenta a la que llega.',
      'Toca **Guardar transferencia**.',
    ],
    action: { label: 'Transferir', kind: 'sheet', sheet: { kind: 'tx', type: 'transfer' } },
    related: ['¿Cómo pago la tarjeta?', '¿Cómo agrego una cuenta?'],
  },
  {
    id: 'registro-rapido',
    kind: 'app',
    triggers: [
      'registro rapido',
      'anotar rapido',
      'anoto rapido',
      'dictar un gasto',
      'anotar con la voz',
      'registrar por voz',
      'dictar con el microfono',
      'hablarle a la app',
    ],
    title: 'Registro rápido escribiendo o con voz',
    answer:
      'En el Inicio toca la barra **Escribe o dicta** y pon algo como "5 lucas en el Uber" o "le presté 10 lucas a mi hermano": la app entiende el monto, el lugar, la cuenta y la fecha. Con el **micrófono** lo dictas por voz (si tu navegador lo permite). También puedes escribírmelo aquí en el chat.',
    steps: [
      'En el Inicio toca **Escribe o dicta: 5 lucas en el Uber**, o el **micrófono** para dictar.',
      'Escribe o di el movimiento, por ejemplo "ayer 12 mil en el Líder con tarjeta".',
      'Revisa **Así lo voy a guardar**; si algo no calza, toca **Editar detalles**.',
      'Toca **Guardar**. Si te equivocaste, toca **Deshacer** en el aviso.',
    ],
    action: { label: 'Registro rápido', kind: 'sheet', sheet: { kind: 'quick' } },
    related: ['¿Cómo registro un gasto?', '¿Cómo deshago un movimiento?'],
  },
  {
    id: 'escanear-boleta',
    kind: 'app',
    triggers: [
      'escanear boleta',
      'escanear una boleta',
      'escaneo una boleta',
      'foto a la boleta',
      'foto de la boleta',
      'leer la boleta',
      'compartir la boleta',
      'boleta de la galeria',
    ],
    title: 'Escanear una boleta',
    answer:
      'Toca **Escanear boleta** en el Inicio y saca una foto o elígela de la galería: la app lee el total, la fecha y el comercio, todo **en tu teléfono**. Si se ve nítido el **timbre** (el código de barras de abajo), el total y la fecha quedan exactos. En Android, con la app instalada, también puedes compartir la foto desde la galería con **Compartir → Mis Finanzas**.',
    steps: [
      'Toca **Escanear boleta** en el Inicio (o dentro de **Nuevo movimiento**).',
      'Elige **Tomar foto** o **Elegir de la galería**.',
      'Revisa el total y **¿Dónde compraste?**, y toca **Continuar**.',
      'Elige con qué pagaste y toca **Guardar gasto**: la foto queda adjunta.',
    ],
    action: { label: 'Escanear boleta', kind: 'sheet', sheet: { kind: 'scan' } },
    related: ['¿Cómo importo la cartola del banco?', '¿Cómo divido una cuenta?'],
  },
  {
    id: 'importar-cartola',
    kind: 'app',
    triggers: [
      'importar cartola',
      'importo la cartola',
      'cartola del banco',
      'subir la cartola',
      'importar movimientos del banco',
      'traer movimientos del banco',
      'cargar excel del banco',
      'importar csv',
    ],
    title: 'Importar la cartola del banco',
    answer:
      'Descarga la cartola o los últimos movimientos desde la app o web de tu banco en **Excel (.xls, .xlsx) o CSV** y súbela en **Importar cartola**. Revisas las columnas, eliges la cuenta y marcas qué movimientos traer; los que ya tenías aparecen como **duplicados**. El archivo se procesa en tu teléfono y no se sube a ningún lado.',
    steps: [
      'Ve a **Más → Ajustes → Importar cartola del banco** (o el ícono de subir archivo en **Movimientos**).',
      'Toca **Elegir archivo** y elige la cartola.',
      'Revisa las columnas y elige **¿De qué cuenta es esta cartola?**',
      'Toca **Revisar movimientos**, marca los que quieras y toca **Importar movimientos**.',
    ],
    action: { label: 'Importar cartola', kind: 'sheet', sheet: { kind: 'import' } },
    related: ['¿Cómo exporto mis movimientos a Excel?', '¿Cómo escaneo una boleta?'],
  },
  {
    id: 'dividir-cuenta',
    kind: 'app',
    triggers: [
      'dividir una cuenta',
      'dividir la cuenta',
      'divido una cuenta',
      'pagar a medias',
      'repartir la cuenta',
      'dividir entre amigos',
      'cada uno paga su parte',
      'dividir el asado',
    ],
    title: 'Dividir una cuenta',
    answer:
      'Sí: con **Dividir cuenta** anotas lo que pagaste y la app calcula cuánto le toca a cada uno, en **partes iguales** o con **montos distintos**. Tu parte queda como gasto y lo de los demás como **préstamos** que te deben; después les cobras por WhatsApp con un toque.',
    steps: [
      'Toca **Dividir cuenta** en el Inicio (o **Dividir** en Préstamos).',
      'Escribe el **Total de la cuenta** y **¿Qué fue?**',
      'En **¿Entre quiénes?** agrega a las personas y deja **Yo también consumí** si tú también consumiste.',
      'Elige **Partes iguales** o **Montos distintos** y con qué pagaste.',
      'Toca **Dividir y guardar** y luego **Cobrar por WhatsApp**.',
    ],
    action: { label: 'Dividir cuenta', kind: 'sheet', sheet: { kind: 'split' } },
    related: ['¿Cómo anoto un préstamo?', '¿Cómo registro un abono?'],
  },

  /* ───────────── Préstamos ───────────── */
  {
    id: 'anotar-prestamo',
    kind: 'app',
    triggers: [
      'anotar un prestamo',
      'anoto un prestamo',
      'registrar un prestamo',
      'nuevo prestamo',
      'agregar un prestamo',
      'le preste plata',
      'me prestaron plata',
      'prestarle a alguien',
    ],
    title: 'Anotar un préstamo',
    answer:
      'Toca **Préstamo** en el Inicio o **Nuevo** en Préstamos y elige **Yo presté** o **Me prestaron**. Si dejas marcado **Salió de una de mis cuentas**, se descuenta de tu saldo pero **no cuenta como gasto**, y vuelve cuando te paguen.',
    steps: [
      'Toca **Préstamo** en el Inicio (o **Más → Préstamos → Nuevo**).',
      'Elige **Yo presté** o **Me prestaron** y escribe el nombre y el monto.',
      'Si quieres, pon una fecha en **Devolver antes de** (1 semana, 15 días o 1 mes).',
      'Toca **Guardar préstamo**.',
    ],
    action: { label: 'Anotar préstamo', kind: 'sheet', sheet: { kind: 'loan' } },
    related: ['¿Cómo registro un abono?', '¿Cómo le cobro por WhatsApp?'],
  },
  {
    id: 'abonar-saldar-prestamo',
    kind: 'app',
    triggers: [
      'registrar un abono',
      'registro un abono',
      'abonar a un prestamo',
      'me pagaron una parte',
      'saldar un prestamo',
      'saldar el prestamo',
      'marcar el prestamo pagado',
      'me devolvieron la plata',
    ],
    title: 'Abonar o saldar un préstamo',
    answer:
      'Abre el préstamo en **Préstamos** y toca **Registrar abono** si te pagaron una parte, o **Saldar todo** si te pagaron completo. Cada abono se registra en la cuenta que elijas y queda en el **Historial de abonos**.',
    steps: [
      'Ve a **Más → Préstamos** y toca el préstamo.',
      'Toca **Registrar abono**, escribe el monto (o elige **25%**, **50%** o **Todo**) y la cuenta.',
      'Toca **Registrar abono** para guardarlo.',
      'Si te pagaron todo de una, toca **Saldar todo** y confirma con **Sí, saldar**.',
    ],
    action: { label: 'Ver préstamos', kind: 'nav', to: '/prestamos' },
    related: ['¿Cómo le cobro por WhatsApp?', '¿Cómo anoto un préstamo?'],
  },
  {
    id: 'recordar-prestamo-whatsapp',
    kind: 'app',
    triggers: [
      'cobrar por whatsapp',
      'le cobro por whatsapp',
      'recordar por whatsapp',
      'recordarle que me debe',
      'recordatorio amistoso',
      'mandar un recordatorio de prestamo',
      'cobrarle a alguien',
    ],
    title: 'Cobrar un préstamo por WhatsApp',
    answer:
      'Abre el préstamo y toca **Enviar recordatorio amistoso**: se arma un mensaje cordial con el monto y la fecha del préstamo, y lo mandas por **WhatsApp** o por la app que elijas. Si eres tú quien debe, el botón dice **Avisarle que le pagarás**.',
    steps: [
      'Ve a **Más → Préstamos** y toca el préstamo.',
      'Toca **Enviar recordatorio amistoso**.',
      'Elige WhatsApp (o la app que quieras) y envía el mensaje.',
    ],
    action: { label: 'Ver préstamos', kind: 'nav', to: '/prestamos' },
    related: ['¿Cómo registro un abono?', '¿Cómo funcionan los préstamos con amigos?'],
  },
  {
    id: 'prestamos-con-amigos',
    kind: 'app',
    triggers: [
      'prestamos con amigos',
      'prestamo compartido',
      'compartir un prestamo',
      'que le aparezca a mi amigo',
      'amigos en la app',
      'prestamo con un amigo',
      'confirmar que me pagaron',
    ],
    title: 'Préstamos con amigos',
    answer:
      'Si tu amigo también tiene cuenta en la app y lo agregaste, el préstamo le aparece en **su** app: ve cuánto te debe, con recordatorio, y un botón **Ya le pagué** para avisarte. Tú confirmas con **Sí, me pagó** o **Todavía no**. Para esto ambos tienen que **iniciar sesión** en **Más → Mi cuenta**.',
    steps: [
      'Inicia sesión en **Más → Mi cuenta** y agrega a tu amigo en **Más → Amigos**.',
      'Toca **Préstamo** junto a su nombre, o en **Nuevo préstamo** elígelo en **Amigos en la app**.',
      'Completa el monto y toca **Guardar y compartir**.',
      'Cuando te avise que pagó, confírmalo en **Amigos → Por confirmar** con **Sí, me pagó**.',
    ],
    action: { label: 'Ir a Amigos', kind: 'nav', to: '/amigos' },
    related: ['¿Cómo agrego a un amigo?', '¿Cómo creo mi cuenta?'],
  },
  {
    id: 'agregar-amigos',
    kind: 'app',
    triggers: [
      'agregar a un amigo',
      'agrego a un amigo',
      'agregar amigos',
      'invitar a un amigo',
      'solicitud de amistad',
      'aceptar la solicitud',
      'compartir mi link',
      'mi nombre de usuario',
    ],
    title: 'Agregar amigos',
    answer:
      'En **Más → Amigos** escribe el **@usuario** de tu amigo y toca **Agregar**, o mándale tu link con **Compartir mi link**. Cuando acepte la solicitud, ya pueden compartirse préstamos. Ambos necesitan **iniciar sesión** en la app.',
    steps: [
      'Inicia sesión en **Más → Mi cuenta**.',
      'Ve a **Más → Amigos**.',
      'Escribe su **@usuario** y toca **Agregar**, o toca **Compartir mi link**.',
      'Tu amigo verá la solicitud en **Solicitudes** y toca **Aceptar**.',
    ],
    action: { label: 'Ir a Amigos', kind: 'nav', to: '/amigos' },
    related: ['¿Cómo funcionan los préstamos con amigos?', '¿Cómo creo mi cuenta?'],
  },

  /* ───────────── Cuenta en la nube ───────────── */
  {
    id: 'crear-cuenta-iniciar-sesion',
    kind: 'app',
    triggers: [
      'crear mi cuenta',
      'creo mi cuenta',
      'iniciar sesion',
      'inicio sesion',
      'registrarme en la app',
      'entrar con google',
      'entrar sin contrasena',
      'cerrar sesion',
    ],
    title: 'Crear tu cuenta o iniciar sesión',
    answer:
      'Ve a **Más → Mi cuenta**, elige **Crear cuenta** y pon tu nombre, un **usuario**, tu correo y una contraseña de al menos 8 caracteres. Si ya tienes cuenta, usa **Iniciar sesión**; también puedes entrar con **un link al correo** o con Google si aparece la opción. Para salir, toca **Cerrar sesión**: tus datos se quedan en el teléfono.',
    steps: [
      'Ve a **Más → Mi cuenta**.',
      'Elige **Crear cuenta** (o **Iniciar sesión** si ya tienes una).',
      'Completa tus datos y toca **Crear cuenta** (o **Entrar**).',
      'Si te llega un correo para confirmar, ábrelo en este mismo teléfono.',
    ],
    action: { label: 'Ir a Mi cuenta', kind: 'nav', to: '/cuenta' },
    related: ['¿Cómo respaldo en la nube?', 'Olvidé mi contraseña, ¿qué hago?'],
  },
  {
    id: 'respaldo-en-la-nube',
    kind: 'app',
    triggers: [
      'respaldo en la nube',
      'respaldar en la nube',
      'cuenta en la nube',
      'sincronizar',
      'usar en el computador',
      'cambiar de telefono',
      'perdi el telefono',
      'otro dispositivo',
    ],
    title: 'Respaldo en la nube',
    answer:
      'Con tu sesión iniciada en **Más → Mi cuenta**, todo se respalda **solo** cada vez que cambias algo, y puedes usar la app en el celular y en el computador con los mismos datos. Para forzarlo, toca **Ahora** en **Respaldo en la nube**. Las fotos de boletas y el PIN quedan solo en este dispositivo.',
    steps: [
      'Ve a **Más → Mi cuenta** e inicia sesión o crea tu cuenta.',
      'En **Respaldo en la nube** ves la última vez que se guardó.',
      'En el otro teléfono o computador, entra con la misma cuenta y tus datos llegan solos.',
    ],
    action: { label: 'Ir a Mi cuenta', kind: 'nav', to: '/cuenta' },
    related: ['¿Cómo descargo un respaldo?', '¿Dónde quedan mis datos?'],
  },
  {
    id: 'olvide-contrasena',
    kind: 'app',
    triggers: [
      'olvide mi contrasena',
      'olvide la contrasena',
      'recuperar mi contrasena',
      'recuperar la contrasena',
      'restablecer la contrasena',
      'cambiar mi contrasena',
      'nueva contrasena',
    ],
    title: 'Olvidé mi contraseña',
    answer:
      'En **Más → Mi cuenta**, en **Iniciar sesión**, toca **¿Olvidaste tu contraseña?**, escribe tu correo y toca **Enviar link**. Abre el link del correo en este teléfono y la app te pedirá **Crea tu nueva contraseña**. Si quieres cambiarla y tienes la sesión abierta, primero toca **Cerrar sesión**.',
    steps: [
      'Ve a **Más → Mi cuenta**.',
      'Toca **¿Olvidaste tu contraseña?** (debajo de la contraseña).',
      'Escribe tu correo y toca **Enviar link** (si no llega, revisa spam o promociones).',
      'Abre el link, escribe la nueva y toca **Guardar contraseña**.',
    ],
    action: { label: 'Ir a Mi cuenta', kind: 'nav', to: '/cuenta' },
    related: ['¿Cómo inicio sesión?', '¿Cómo respaldo en la nube?'],
  },

  /* ───────────── Tarjetas de crédito ───────────── */
  {
    id: 'agregar-tarjeta-credito',
    kind: 'app',
    triggers: [
      'agregar tarjeta de credito',
      'agregar mi tarjeta',
      'agrego mi tarjeta',
      'registrar tarjeta de credito',
      'nueva tarjeta de credito',
      'donde pongo el cupo',
      'dia de facturacion',
      'configurar la tarjeta',
    ],
    title: 'Agregar una tarjeta de crédito',
    answer:
      'Las tarjetas se agregan como una cuenta de tipo **Tarjeta de crédito**. Ahí pones la deuda actual, el **cupo total**, el **día de facturación** (cuando cierra el estado de cuenta) y el **día de pago**; con eso la app calcula tu cupo disponible y cuánto pagar cada mes.',
    steps: [
      'Toca **Nueva cuenta** en el Inicio (o **Más → Cuentas → Nueva**).',
      'En **Tipo** elige **Tarjeta de crédito** y ponle nombre.',
      'Escribe la **Deuda actual de la tarjeta** y el **Cupo total de la tarjeta**.',
      'Elige el **Día de facturación** y el **Día de pago** (salen en tu estado de cuenta) y toca **Crear cuenta**.',
    ],
    action: { label: 'Agregar tarjeta', kind: 'sheet', sheet: { kind: 'account' } },
    related: ['¿Cómo anoto una compra en cuotas?', '¿Cómo pago la tarjeta?'],
  },
  {
    id: 'compras-en-cuotas',
    kind: 'app',
    triggers: [
      'compra en cuotas',
      'compras en cuotas',
      'comprar en cuotas',
      'pagar en cuotas',
      'anotar en cuotas',
      'registrar las cuotas',
    ],
    title: 'Compras en cuotas',
    answer:
      'Registra el gasto normal y en **Pagaste con** elige tu tarjeta de crédito: aparece **Cuotas** para elegir en cuántas (entre 2 y 36). La app reparte el monto en tus próximos estados de cuenta, y en el detalle de la tarjeta ves cuántas cuotas van y cuánto falta.',
    steps: [
      'Toca el botón **+** y escribe el monto total de la compra.',
      'En **Pagaste con** elige tu **tarjeta de crédito**.',
      'En **Cuotas** elige cuántas (por ejemplo **6 cuotas**).',
      'Toca **Guardar gasto**.',
    ],
    action: { label: 'Registrar compra', kind: 'sheet', sheet: { kind: 'tx', type: 'expense' } },
    related: ['¿Cómo pago la tarjeta?', '¿Cómo agrego mi tarjeta?'],
  },
  {
    id: 'pagar-tarjeta',
    kind: 'app',
    triggers: [
      'pagar la tarjeta',
      'pago la tarjeta',
      'pagar tarjeta de credito',
      'registrar el pago de la tarjeta',
      'aviso de pago de tarjeta',
      'recordatorio de la tarjeta',
      'avisar el pago de la tarjeta',
    ],
    title: 'Pagar la tarjeta de crédito',
    answer:
      'Paga en la app de tu banco y después regístralo aquí: en **Más → Cuentas** toca tu tarjeta y luego **Pagar tarjeta**. Se arma una transferencia con el monto a pagar y solo eliges desde qué cuenta salió. Para que te avise antes del vencimiento, activa **Pago de tarjetas** en **Ajustes → Recordatorios**.',
    steps: [
      'Ve a **Más → Cuentas** y toca tu tarjeta de crédito.',
      'Revisa **Próximo pago**: el monto y la fecha de vencimiento.',
      'Toca **Pagar tarjeta**, elige en **Desde** la cuenta con que pagaste y toca **Guardar transferencia**.',
    ],
    action: { label: 'Ver mis tarjetas', kind: 'nav', to: '/cuentas' },
    related: ['¿Cómo activo los recordatorios?', '¿Cómo anoto una compra en cuotas?'],
  },

  /* ───────────── Cuentas, categorías, presupuestos, metas, suscripciones ───────────── */
  {
    id: 'cuentas',
    kind: 'app',
    triggers: [
      'agregar una cuenta',
      'agrego una cuenta',
      'nueva cuenta',
      'editar una cuenta',
      'archivar una cuenta',
      'borrar una cuenta',
      'eliminar una cuenta',
      'corregir el saldo',
    ],
    title: 'Agregar, editar o archivar cuentas',
    answer:
      'En **Más → Cuentas** toca **Nueva**, elige el tipo (Efectivo, Débito / Cuenta Vista, Tarjeta de crédito, Ahorro, Inversión u Otra) y escribe cuánto tienes hoy. Para editarla o **corregir el saldo**, tócala y cambia lo que necesites (se ajusta sin tocar tus movimientos). Con el **basurero** la archivas si tiene movimientos, y conservas el historial, o la eliminas si está vacía.',
    steps: [
      'Ve a **Más → Cuentas** y toca **Nueva** (o **Nueva cuenta** en el Inicio).',
      'Elige el **Tipo**, ponle **Nombre** y escribe **¿Cuánto tienes hoy?**',
      'Toca **Crear cuenta**.',
      'Para editarla, tócala (en tarjetas, toca **Editar**); para archivarla, toca el basurero y confirma **Archivar**.',
      'Las archivadas aparecen abajo en **Archivadas** y se recuperan con **Desarchivar**.',
    ],
    action: { label: 'Ir a Cuentas', kind: 'nav', to: '/cuentas' },
    related: ['¿Cómo agrego mi tarjeta?', '¿Cómo transfiero entre mis cuentas?'],
  },
  {
    id: 'categorias',
    kind: 'app',
    triggers: [
      'crear una categoria',
      'creo una categoria',
      'nueva categoria',
      'agregar una categoria',
      'editar una categoria',
      'borrar una categoria',
      'eliminar una categoria',
      'icono de una categoria',
    ],
    title: 'Crear o editar categorías',
    answer:
      'En **Más → Categorías** elige **Gastos** o **Ingresos** y toca **Nueva**: le pones nombre, ícono, color y, si quieres, un **presupuesto mensual**. Tócala para editarla; si la eliminas, sus movimientos quedan **Sin categoría**. También puedes crear una al vuelo desde el formulario del gasto con **Nueva**.',
    steps: [
      'Ve a **Más → Categorías**.',
      'Elige **Gastos** o **Ingresos** y toca **Nueva**.',
      'Escribe el **Nombre** y elige **Ícono** y **Color**.',
      'Toca **Guardar**.',
    ],
    action: { label: 'Nueva categoría', kind: 'sheet', sheet: { kind: 'category' } },
    related: ['¿Cómo pongo un presupuesto?', '¿Cómo cambio la categoría de un movimiento?'],
  },
  {
    id: 'presupuestos',
    kind: 'app',
    triggers: [
      'crear un presupuesto',
      'agregar un presupuesto',
      'poner un presupuesto',
      'pongo un presupuesto',
      'definir un presupuesto',
      'presupuesto por categoria',
      'limite mensual',
      'quitar el presupuesto',
      'cambiar el presupuesto',
    ],
    title: 'Presupuestos total y por categoría',
    answer:
      'En **Más → Presupuestos** puedes definir un **límite total del mes** y también uno **por categoría**. La app te muestra cuánto te queda y cuánto puedes gastar por día, te sugiere un monto según tu historial y te avisa al llegar al **80 %** y al pasarte.',
    steps: [
      'Ve a **Más → Presupuestos**.',
      'Para el total, toca **Definir límite**, escribe el **Límite por mes** y toca **Guardar**.',
      'Para una categoría, tócala en **Agregar presupuesto a…** y guarda su límite.',
      'Para cambiarlo o quitarlo, toca el presupuesto y usa **Guardar** o **Quitar**.',
    ],
    action: { label: 'Ir a Presupuestos', kind: 'nav', to: '/presupuestos' },
    related: ['¿Cómo activo los recordatorios?', '¿Cómo creo una categoría?'],
  },
  {
    id: 'metas-de-ahorro',
    kind: 'app',
    triggers: [
      'crear una meta',
      'agregar una meta',
      'creo una meta',
      'nueva meta',
      'ahorrar para algo',
      'apartar dinero',
      'abonar a una meta',
      'agregar plata a la meta',
      'retirar de una meta',
    ],
    title: 'Metas de ahorro',
    answer:
      'En **Más → Metas de ahorro** toca **Nueva**, ponle nombre, cuánto necesitas y, si quieres, para cuándo: la app te dice **cuánto apartar al mes**. Para sumarle plata toca **Apartar dinero**. Lo apartado es una reserva: **no se descuenta** de tus cuentas, pero se muestra en el Inicio para que no lo gastes.',
    steps: [
      'Ve a **Más → Metas de ahorro** y toca **Nueva**.',
      'Completa **¿Para qué estás ahorrando?**, **¿Cuánto necesitas?** y, si quieres, **¿Para cuándo?**',
      'Toca **Guardar meta**.',
      'Cuando ahorres, toca **Apartar dinero** en la meta (o elige **Retirar** si sacas plata).',
    ],
    action: { label: 'Crear meta', kind: 'sheet', sheet: { kind: 'goal' } },
    related: ['¿Cómo pongo un presupuesto?', '¿Cómo funciona la salud financiera?'],
  },
  {
    id: 'suscripciones',
    kind: 'app',
    triggers: [
      'agregar una suscripcion',
      'agrego una suscripcion',
      'nueva suscripcion',
      'agregar un pago fijo',
      'cobro automatico',
      'se anota sola',
      'marcar suscripcion pagada',
      'pausar una suscripcion',
    ],
    title: 'Suscripciones y cobro automático',
    answer:
      'En **Más → Suscripciones** toca **Nueva**, elige una popular o escribe el nombre, el monto, la frecuencia y el **Próximo cobro**. Si dejas encendido **Registrar el gasto automáticamente**, el gasto se anota solo cuando llega la fecha; si lo apagas, cuando llegue el cobro tocas **Marcar pagado** u **Omitir**.',
    steps: [
      'Ve a **Más → Suscripciones** y toca **Nueva**.',
      'Elige una de **Populares** o escribe el **Nombre** y el **Monto de cada cobro**.',
      'Elige **Frecuencia**, **Próximo cobro** y **Se paga con**.',
      'Deja **Registrar el gasto automáticamente** como prefieras y toca **Agregar suscripción**.',
      'Si la cancelaste, ábrela y apaga **Activa**.',
    ],
    action: { label: 'Agregar suscripción', kind: 'sheet', sheet: { kind: 'sub' } },
    related: ['¿Cómo activo los recordatorios?', '¿Cómo pongo un presupuesto?'],
  },

  /* ───────────── Ajustes ───────────── */
  {
    id: 'recordatorios-notificaciones',
    kind: 'app',
    triggers: [
      'activar recordatorios',
      'activar los recordatorios',
      'activo los recordatorios',
      'activar notificaciones',
      'notificaciones',
      'avisos de cobros',
      'probar notificacion',
      'no me llegan los avisos',
    ],
    title: 'Recordatorios y notificaciones',
    answer:
      'En **Ajustes → Recordatorios** enciende el interruptor y acepta el permiso: te avisamos de cobros de suscripciones, préstamos que vencen, pago de tarjetas y presupuestos al límite. Eliges si avisar los cobros el **mismo día, 1 día antes o 3 días antes**. En iPhone, primero tienes que **agregar la app a la pantalla de inicio**.',
    steps: [
      'Ve a **Más → Ajustes** y busca **Recordatorios**.',
      'Enciende el interruptor y acepta el permiso de notificaciones.',
      'Elige qué avisar y en **Avisar los cobros** con cuánta anticipación.',
      'Toca **Probar notificación** para revisar que lleguen.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo instalo la app?', '¿Cómo funciona el cobro automático?'],
  },
  {
    id: 'pin-bloqueo',
    kind: 'app',
    triggers: [
      'poner un pin',
      'pongo un pin',
      'activar el pin',
      'bloqueo con pin',
      'bloquear la app',
      'clave para entrar',
      'olvide mi pin',
      'quitar el pin',
    ],
    title: 'Bloqueo con PIN',
    answer:
      'En **Ajustes → Bloqueo con PIN** toca **Activar** y elige un PIN de 4 dígitos (lo repites para confirmar). Se pide al abrir la app y al volver después de más de un minuto. Ojo: si lo olvidas, la única forma de entrar es **borrar los datos** de la app en el teléfono, así que ten un respaldo.',
    steps: [
      'Ve a **Más → Ajustes** → **Apariencia y privacidad**.',
      'En **Bloqueo con PIN** toca **Activar**.',
      'Escribe tu PIN de 4 dígitos y repítelo.',
      'Para sacarlo, toca **Quitar** en el mismo lugar.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo oculto los montos?', '¿Cómo descargo un respaldo?'],
  },
  {
    id: 'ocultar-montos',
    kind: 'app',
    triggers: [
      'ocultar los montos',
      'ocultar montos',
      'oculto los montos',
      'esconder los montos',
      'que no se vean los montos',
      'mostrar los montos',
      'modo privado',
      'el ojo del inicio',
    ],
    title: 'Ocultar los montos',
    answer:
      'Toca el **ojo** arriba a la derecha en el Inicio, o enciende **Ocultar montos** en **Ajustes**. Los montos se ven como puntitos y las notificaciones tampoco muestran cifras; tócalo de nuevo para mostrarlos.',
    steps: [
      'En el Inicio, toca el ícono del **ojo** (arriba a la derecha).',
      'O ve a **Más → Ajustes** y enciende **Ocultar montos**.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo pongo un PIN?', '¿Cómo activo el tema oscuro?'],
  },
  {
    id: 'tema-oscuro',
    kind: 'app',
    triggers: ['tema oscuro', 'modo oscuro', 'modo claro', 'tema claro', 'cambiar el tema', 'fondo negro', 'modo noche'],
    title: 'Tema oscuro o claro',
    answer:
      'En **Ajustes → Apariencia y privacidad**, en **Tema**, elige **Oscuro**, **Claro** o **Auto** (sigue lo que tenga configurado tu teléfono).',
    steps: ['Ve a **Más → Ajustes**.', 'En **Tema** toca **Oscuro**, **Claro** o **Auto**.'],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo cambio la moneda?', '¿Cómo oculto los montos?'],
  },
  {
    id: 'cambiar-moneda',
    kind: 'app',
    triggers: [
      'cambiar la moneda',
      'cambio la moneda',
      'otra moneda',
      'usar dolares',
      'cambiar a dolares',
      'cambiar a euros',
      'moneda de la app',
    ],
    title: 'Cambiar la moneda',
    answer:
      'En **Ajustes → Perfil → Moneda** elige entre peso chileno, dólar, euro y otras monedas de la región. Solo cambia cómo se muestran los montos: **no convierte** lo que ya anotaste.',
    steps: ['Ve a **Más → Ajustes**.', 'En **Perfil**, abre **Moneda** y elige la tuya.'],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo activo el tema oscuro?'],
  },
  {
    id: 'respaldo-archivo',
    kind: 'app',
    triggers: [
      'descargar un respaldo',
      'descargo un respaldo',
      'descargar respaldo',
      'restaurar el respaldo',
      'restaurar respaldo',
      'copia de seguridad',
      'hacer un respaldo',
      'pasar mis datos a otro telefono',
    ],
    title: 'Respaldo en archivo',
    answer:
      'En **Ajustes → Tus datos** toca **Descargar respaldo** y guarda el archivo en un lugar seguro (por ejemplo, mándatelo por correo). Para recuperarlo, toca **Restaurar respaldo** y elige ese archivo: **reemplaza todos los datos actuales**. El archivo no incluye las fotos de boletas ni tu PIN.',
    steps: [
      'Ve a **Más → Ajustes** → **Tus datos**.',
      'Toca **Descargar respaldo**.',
      'En el otro teléfono (o cuando lo necesites), toca **Restaurar respaldo** y elige el archivo.',
      'Confirma con **Restaurar**.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo respaldo en la nube?', '¿Cómo exporto mis movimientos a Excel?'],
  },
  {
    id: 'exportar-excel',
    kind: 'app',
    triggers: [
      'exportar a excel',
      'exportar mis movimientos',
      'exporto mis movimientos',
      'exportar movimientos',
      'descargar en excel',
      'exportar csv',
      'sacar un excel',
      'planilla de gastos',
    ],
    title: 'Exportar a Excel (CSV)',
    answer:
      'Toca **Exportar movimientos a Excel (CSV)** en **Ajustes → Tus datos**, o el ícono de descarga arriba en **Movimientos**. Se baja un archivo CSV con todos tus movimientos (fecha, tipo, monto, categoría, cuenta, lugar y nota) que abres en Excel o Google Sheets.',
    steps: [
      'Ve a **Movimientos** y toca el ícono de **descarga** (arriba a la derecha).',
      'O ve a **Más → Ajustes** y toca **Exportar movimientos a Excel (CSV)**.',
      'Abre el archivo en Excel o Google Sheets.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo importo la cartola del banco?', '¿Cómo descargo un respaldo?'],
  },
  {
    id: 'instalar-app',
    kind: 'app',
    triggers: [
      'instalar la app',
      'instalo la app',
      'descargar la app',
      'agregar a la pantalla de inicio',
      'pantalla principal',
      'instalar en el iphone',
      'instalar en android',
      'icono en el celular',
    ],
    title: 'Instalar la app',
    answer:
      'En Android, abre el menú **⋮** de Chrome y toca **Instalar app** o **Agregar a la pantalla principal** (o el botón **Instalar app** en Ajustes, si aparece). En iPhone, ábrela en **Safari**, toca **Compartir** y luego **Agregar a inicio**. Queda como una app normal y **funciona sin internet**.',
    steps: [
      'Ve a **Más → Ajustes** → **Instalar en tu teléfono**.',
      'Si aparece, toca **Instalar app**.',
      'Si no, sigue los pasos que salen ahí para Android (menú **⋮**) o iPhone (**Compartir → Agregar a inicio**).',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Qué son los accesos directos del ícono?', '¿Cómo actualizo la app?'],
  },
  {
    id: 'cambiar-mi-nombre',
    kind: 'app',
    triggers: ['cambiar mi nombre', 'cambio mi nombre', 'mi nombre', 'como me llamo en la app'],
    title: 'Cambiar tu nombre',
    answer:
      'Tu nombre está en **Ajustes → Perfil → Tu nombre**. Si tienes cuenta, el nombre que ven tus amigos se cambia en **Más → Mi cuenta → Editar**.',
    steps: ['Ve a **Más → Ajustes**.', 'En **Perfil**, cambia **Tu nombre**.'],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo le cambio el nombre al asistente?'],
  },
  {
    id: 'actualizar-app',
    kind: 'app',
    triggers: [
      'actualizar la app',
      'actualizo la app',
      'nueva version',
      'ultima version',
      'version de la app',
      'la app no se actualiza',
      'app desactualizada',
      'se cae la app',
      'se me cae la app',
      'se cayo la app',
      'se me cayo la app',
      'la app no funciona',
      'la app falla',
      'pantalla en negro',
      'se queda pegada',
    ],
    title: 'Actualizar la app',
    answer:
      'La app se actualiza sola cuando la abres con internet. Si ves algo raro o quieres la última versión al tiro, ve a **Ajustes** y toca **Actualizar app** (abajo, en **Zona de pruebas**): se recarga **sin borrar tus datos**.',
    steps: [
      'Ve a **Más → Ajustes**.',
      'Baja hasta **Zona de pruebas** y toca **Actualizar app**.',
      'Ahí mismo ves la **Versión** y la fecha en que se publicó.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo instalo la app?'],
  },

  /* ───────────── Movimientos y análisis ───────────── */
  {
    id: 'editar-borrar-movimiento',
    kind: 'app',
    triggers: [
      'editar un movimiento',
      'editar un gasto',
      'corregir un gasto',
      'borrar un gasto',
      'eliminar un movimiento',
      'deshacer',
      'deshago un movimiento',
      'categoria de un movimiento',
    ],
    title: 'Editar, borrar o deshacer un movimiento',
    answer:
      'Toca el movimiento en **Movimientos** (o en el Inicio), cambia lo que necesites —monto, categoría, cuenta, fecha o nota— y toca **Guardar cambios**. Para borrarlo toca el **basurero** y confirma **Eliminar**; si te arrepientes, toca **Deshacer** en el aviso que aparece abajo.',
    steps: [
      'Ve a **Movimientos** y toca el movimiento.',
      'Corrige lo que quieras y toca **Guardar cambios**.',
      'Para borrarlo, toca el **basurero** y luego **Eliminar**.',
      'Si fue sin querer, toca **Deshacer** en el aviso de abajo (dura unos segundos).',
    ],
    action: { label: 'Ver movimientos', kind: 'nav', to: '/movimientos' },
    related: ['¿Cómo busco un movimiento?'],
  },
  {
    id: 'buscar-filtrar-movimientos',
    kind: 'app',
    triggers: [
      'buscar un movimiento',
      'busco un movimiento',
      'buscar un gasto',
      'filtrar movimientos',
      'filtrar por categoria',
      'filtrar por cuenta',
      'ver meses anteriores',
      'ver otro mes',
    ],
    title: 'Buscar y filtrar movimientos',
    answer:
      'En **Movimientos** toca la **lupa** y escribe un lugar, nota, categoría o monto: busca en **todo tu historial**. También puedes filtrar por **Gastos, Ingresos o Transferencias**, por **Categorías** y **Cuentas**, y cambiar de mes con las flechas.',
    steps: [
      'Ve a **Movimientos**.',
      'Toca la **lupa** y escribe lo que buscas.',
      'Usa **Todos, Gastos, Ingresos, Transferencias** y las listas **Categorías** y **Cuentas** para filtrar.',
      'Cambia de mes con las flechas de arriba.',
    ],
    action: { label: 'Ver movimientos', kind: 'nav', to: '/movimientos' },
    related: ['¿Cómo exporto mis movimientos a Excel?', '¿Cómo puedo editar un movimiento?'],
  },
  {
    id: 'analisis-salud-financiera',
    kind: 'app',
    triggers: [
      'que es la salud financiera',
      'como funciona la salud financiera',
      'como se calcula la salud financiera',
      'puntaje de salud',
      'pantalla de analisis',
      'graficos de gastos',
      'calendario de gastos',
      'ritmo de gasto',
    ],
    title: 'Análisis y salud financiera',
    answer:
      'En **Análisis** (barra de abajo) ves tu **Salud financiera** de 0 a 100, consejos y alertas, ingresos vs gastos de los últimos 6 meses, el ritmo de gasto, un calendario y dónde más gastas. El puntaje suma **Ahorro** (hasta 35), **Presupuestos** (25), **Tendencia** (20) y **Deudas** (20); toca **Ver cómo se calcula** para ver el detalle.',
    steps: [
      'Toca **Análisis** en la barra de abajo.',
      'Toca **Ver cómo se calcula** en la Salud financiera.',
      'Toca un mes o un día en los gráficos para ver el detalle.',
    ],
    action: { label: 'Ver análisis', kind: 'nav', to: '/analisis' },
    related: ['¿Qué puedes hacer?', '¿Cómo pongo un presupuesto?'],
  },
  {
    id: 'datos-ejemplo-borrar-todo',
    kind: 'app',
    triggers: [
      'datos de ejemplo',
      'cargar ejemplo',
      'probar la app',
      'borrar todos los datos',
      'borrar todo',
      'empezar de cero',
      'reiniciar la app',
      'resetear la app',
    ],
    title: 'Datos de ejemplo y borrar todo',
    answer:
      'En **Ajustes → Zona de pruebas**, **Cargar datos de ejemplo** reemplaza tus datos por 4 meses de movimientos de muestra para que explores, y **Borrar todos los datos** deja la app vacía. Ninguna de las dos se puede deshacer: **descarga un respaldo antes** si quieres conservar lo tuyo.',
    steps: [
      'Ve a **Más → Ajustes** y baja hasta **Zona de pruebas**.',
      'Toca **Cargar datos de ejemplo** o **Borrar todos los datos**.',
      'Confirma en el mensaje que aparece.',
    ],
    action: { label: 'Ir a Ajustes', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo descargo un respaldo?'],
  },

  /* ───────────── El asistente y la app ───────────── */
  {
    id: 'que-puede-hacer-asistente',
    kind: 'app',
    triggers: [
      'que puedes hacer',
      'que sabes hacer',
      'como funciona el asistente',
      'para que sirves',
      'en que me puedes ayudar',
      'que te puedo preguntar',
    ],
    title: 'Lo que puede hacer el asistente',
    answer:
      'Respondo con **tus datos**: cuánto gastaste en algo o en un lugar, cómo vas este mes, en qué gastas más, quién te debe, tus suscripciones, tarjetas, presupuestos, metas y los pagos que se vienen. También anoto gastos si me escribes "gasté 5 lucas en uber" y te explico cómo usar la app. Funciono **sin internet** y nada sale de tu teléfono.',
    related: ['¿Cómo te cambio la personalidad?', '¿Cómo anoto rápido escribiendo?'],
  },
  {
    id: 'personalidad-asistente',
    kind: 'app',
    triggers: [
      'cambiar la personalidad',
      'cambio la personalidad',
      'tu personalidad',
      'cambiarte el nombre',
      'cambiar tu nombre',
      'ponerte otro nombre',
      'que hables mas serio',
      'que seas mas chistoso',
    ],
    title: 'Cambiar mi nombre y personalidad',
    answer:
      'Toca **Personalidad** (la carita de arriba a la derecha en esta pantalla) para ponerme otro nombre y elegir cómo hablo: **Buena onda**, **Profesional**, **Coach** o **Chistoso**. Los números son los mismos; solo cambia el tono.',
    steps: [
      'En el asistente, toca **Personalidad** (la carita de arriba).',
      'Escribe el **Nombre del asistente** que quieras.',
      'Elige una personalidad y toca **Listo**.',
    ],
    related: ['¿Qué puedes hacer?'],
  },
  {
    id: 'accesos-directos',
    kind: 'app',
    triggers: [
      'accesos directos',
      'acceso directo',
      'mantener presionado el icono',
      'atajos de la app',
      'atajo para escanear',
      'atajo en el icono',
    ],
    title: 'Accesos directos del ícono',
    answer:
      'En Android, con la app instalada, **mantén presionado su ícono** y aparecen atajos: **Nuevo gasto**, **Escanear boleta**, **Dividir una cuenta** y **Préstamos**. Así llegas directo, sin pasar por el Inicio.',
    steps: [
      'Instala la app (**Más → Ajustes → Instalar en tu teléfono**).',
      'Mantén presionado el ícono de la app en tu pantalla de inicio.',
      'Toca el atajo que quieras.',
    ],
    action: { label: 'Instalar la app', kind: 'nav', to: '/ajustes' },
    related: ['¿Cómo instalo la app?', '¿Cómo escaneo una boleta?'],
  },
  {
    id: 'privacidad-datos',
    kind: 'app',
    triggers: [
      'donde quedan mis datos',
      'donde se guardan mis datos',
      'privacidad',
      'mis datos son privados',
      'mis datos estan seguros',
      'quien ve mis datos',
      'es segura la app',
      'se sube a internet',
    ],
    title: 'Dónde quedan tus datos',
    answer:
      'Tus datos se guardan **en este dispositivo**. Si inicias sesión en **Mi cuenta**, además se respaldan en tu cuenta en la nube para que no los pierdas, pero las **fotos de boletas** y el **PIN** quedan solo en el teléfono. Las boletas, las cartolas que importas y este asistente se procesan en tu teléfono, sin enviar nada a ningún lado.',
    related: ['¿Cómo respaldo en la nube?', '¿Cómo pongo un PIN?'],
  },
]
